---
#- name: change version python to 27
#  shell: "ln -fs /usr/bin/python2 /usr/bin/python"

#- name: yum update
#  shell: 'yum update -y'
  
#- name: copy local container-selinux
#  copy:
#    src: "{{ line2_item }}"
#    dest: "/tmp"
#    mode: 0775
#  with_fileglob:
#    - "files/container-selinux*el7*.noarch.rpm"
#  loop_control:
#    loop_var: line2_item

#- name: Finding RPM files
#  find:
#    paths: "/tmp"
#    patterns: "*.rpm"
#  register: rpm_result

#- name: Install RPM
#  yum:
#    name: "{{ line1_item.path }}"
#    state: present
#  with_items: "{{ rpm_result.files }}"
#  loop_control:
#    loop_var: line1_item

- name: Install packages
  package:
    name: "{{ line_item }}"
    state: present
  loop:
# - "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"
  - "{{ docker_packages['EL7'] }}"
  when: docker_repo is success
  loop_control:
    loop_var: line_item

#- name: reinstall pip
#  command: "pip install --upgrade --force-reinstall pip==19.1.1"

#yum install http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
#- name: change version python to 36
#  shell: "ln -fs /usr/bin/python3 /usr/bin/python"

- name: upgrade pip
  shell: "pip install --upgrade pip"

- name: Installing docker-compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_v }}"
    state: present
    extra_args: '--quiet'
 #   executable: pip-3.6
  when: (docker_compose_install == "yes")
  notify: restart docker


