---  
- name: Create user
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups }}"
    append: "yes"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/{{ item.username }}
  when: 'item.username != ""'
  with_items: "{{users}}"
  ignore_errors: yes 

- name: Set authorized key took from file
  authorized_key:
    user: "{{ item.0.username }}"
    state: present
    key: "{{ lookup('file', item.1) }}"
  with_subelements: 
    - "{{ users }}"
    - pub_key
    - flags:
      skip_missing: True

- name: Update user passwords
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ users }}"
  when: item.password is defined
 
- name: accept new ssh fingerprints
  shell: "ssh-keyscan -H {{hostvars[item]['ansible_default_ipv4']['address']}} >> ~/.ssh/known_hosts"
  become_user: jenkins
  with_items:
  - "{{ groups['kube'] }}"
