---  
- name: test
  command: 'setenforce 0'
  become: true 
  
- name: Set authorized keys taken from url
  authorized_key:
    user: charlie
    state: present
    key: "{{ item.pub_key }}"
  with_items: 
    - "{{ users }}"
 

  
- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  user:
    name: shvydkiyvg
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    shell: /bin/bash
  become: yes 
  
- name: Create user
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups }}"
    append: "yes"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/{{ item.username }}
  when: 'item.username != ""'
  with_items: "{{users}}"
  ignore_errors: yes 

- name: Set authorized key took from file
  authorized_key:
    user: "{{ item.0.username }}"
    state: present
    key: "{{ lookup('file', item.1) }}"
  with_subelements: 
    - "{{ users }}"
    - pub_key
    - flags:
      skip_missing: True

- name: Update user passwords
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ users }}"
  when: item.password is defined
