---
postgresql_version: "9.6"
postgresql_version_nodots: "96"
PGDATA96: "/data/pgsql/{{ postgresql_version_nodots }}"
postgresql_daemon: "postgresql"
postgresql_restarted_state: "restarted"
postgresql_bin_path: "/usr/pgsql-{{ postgresql_version }}/bin"

# INSTALL
#==============================================================================
postgresql_packages:
  - "postgresql{{ postgresql_version_nodots }}"
  - "postgresql{{ postgresql_version_nodots }}-server"
  - "postgresql{{ postgresql_version_nodots }}-contrib"
  - "postgresql{{ postgresql_version_nodots }}-libs"
  - "postgresql{{ postgresql_version_nodots }}-devel"
  - "python-psycopg2"
  - "postgis24_{{ postgresql_version_nodots }}"

pg_dir:
  - "/var/lib/pgsql/.ansible/tmp"
  - "/home/postgres/.ansible/tmp"
  - "{{ PGDATA96 }}"




# NETWORK
#==============================================================================
pg_network: "{{ groups['pg'][0] }}"
  
# postgresql.conf
#==============================================================================
listen_addresses: "*"

# pg_hba.conf
#============================================================================
# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
# TYPE  DATABASE        USER            ADDRESS                 METHOD
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
#  - {type: host, database: all, user: all, address: '{{ master_ip }}/26', auth_method: md5}

