---
- name: restart mongo
  service:
    name: mongod
    state: restarted
    enabled: yes

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart graylog-server
  service:
    name: graylog-server
    state: restarted
    enabled: yes
