#The following tasks initiate a Docker Swarm and then save the master and worker tokens so we can add more hosts to the cluster.

- name: "create primary swarm manager"
  shell: "docker swarm init --advertise-addr {{ manager_first }}"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

- name: "get docker swarm manager token"
  shell: "docker swarm join-token -q manager"
  register: manager_token

- name: "get docker swarm worker token"
  shell: "docker swarm join-token -q worker"
  register: worker_token