---
samba_dir: "/data/samba" # for download
samba_version: "4.11.2" # need python3
samba_install_dir: "{{ samba_dir }}/samba-{{ samba_version }}"
samba_url: "https://download.samba.org/pub/samba/stable/samba-{{ samba_version }}.tar.gz"


#configure_opts: "--enable-selftest --prefix=/usr --enable-fhs --with-systemd --with-configdir=/etc/samba --enable-cups --with-acl-support --with-ads --with-automount --with-pam --with-quotas --with-syslog --with-utmp --with-dnsupdate --enable-debug --with-winbind"
realm: "company.ru"
domain: "COMPANY"
server_role: "dc" #domain controller
dns_backend: "SAMBA_INTERNAL" # if use BIND9_DLZ - dont need use dns_forwarder or if use SAMBA_INTERNAL add dns_forwarder
dns_forwarder: "8.8.8.8" # !!!! dont use with BIND9_DLZ on dns_backend
admin_password: "MyPassword123"
config_domain: "--use-rfc2307 --realm={{ realm }} --domain={{ domain }} --server-role={{ server_role }} --adminpass={{ admin_password }} --dns_forwarder={{ dns_forwarder }} "

path_named_conf: "/usr/var/lib/samba/bind-dns/named.conf"

# Main config file - CENTOS
bind_config: /etc/named.conf

samba_packages:
  EL7:
  - epel-release
  - nano
  - samba
  - samba-libs
  - samba-common
  - samba-common-libs
  - samba-dc
  - samba-dc-lib
  - samba-winbind
  - python3-dns
  - bind 
  - bind-sdb





# Defines if groups defined in samba_domain_groups list should be created
samba_create_domain_groups: false

# Define samba groups to create
samba_groups:
  [testgroup]
  # - testgroup
  # - nogroup
  # - securedgroup


# Defines if users defined in samba_domain_users list should be created
samba_create_domain_users: true

samba_domain_users:
  - name: test01
    password: P@55w0rd
  # - name: test01
  #   password: P@55w0rd
  # - name: test02
  #   password: P@55w0rd

samba_packages:
  EL7:
  - epel-release
  - samba-libs
  - autoconf 
  - automake 
  - bind-utils
  - python3
  - python3-devel
  - gcc
  - gdb 
  - perl
  - make
  - krb5-workstation
  - pygpgme
  - libxslt
  - docbook-style-xsl
  - pam-devel
  - lmdb-devel
  - libblkid-devel
  - libarchive-devel
  - libacl-devel
  - readline-devel
  - krb5-devel
  - gnutls-devel
  - gpgme-devel 
  - jansson-devel
  - cups-devel
  - openldap-devel
  - zlib-devel
  - policycoreutils-python
  - libsemanage-python

