---
- name: "Allow traffic for Application"
  ufw:
    rule: allow
    name: bind9

- name: "Allow all DNS traffic on port 53/tcp"
  ufw:
    rule: allow
    port: '53'
    proto: "{{ item }}"
  with_items:
    - tcp
    - udp

