---
- name: SFTP-Server | Create sftp user's group
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ sftp_users | selectattr('group', 'defined') | map(attribute='group') | list }}"

# Create each SFTP user with home directory on the correct partition, and add to SFTP group.
- name: SFTP-Server | Create sftp users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ sftp_group_name }}"
    append: "{{ item.append | default(False) }}"
    home: "{{ sftp_home_partition }}/{{ item.name }}"
    # `None` means default value -> default is to have a shell
    shell: "{{ None if (item.shell | default(True)) else sftp_nologin_shell }}"
    skeleton: "{{ item.skeleton | default(omit) }}"
    state: present
  with_items: "{{ sftp_users }}"

# A working chrooted SFTP setup requires root:sftgroup ownership of a user's home directory.
- name: SFTP-Server | Correct ownership and permission of home directories
  file:
    path: "{{ sftp_home_partition }}/{{ item.name }}"
    owner: root
    group: "{{ item.group | default(sftp_group_name) }}"
    mode: "{{ item.mode | default(0750) }}"
  with_items: "{{ sftp_users }}"

# Install all relevant public keys.
- name: SFTP-Server | Install public keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{ sftp_users }}"
    - authorized
    - flags:
      skip_missing: True

# Update user passwords, if they were specified.
- name: SFTP-Server | Update user passwords
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  with_items: "{{ sftp_users }}"
  when: item.password is defined

# Create directories for all SFTP users. Optional, but recommended.
- name: SFTP-Server | Create directories
  file:
    path: "{{ sftp_home_partition }}/{{ item[0].name }}/{{ item[1].name | default(item[1]) }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].group | default(item[0].name) }}"
    mode: "{{ item[1].mode | default(0750) }}"
    state: directory
  with_nested:
    - "{{ sftp_users }}"
    - "{{ sftp_directories }}"

# Create directories for individual SFTP users. Optional.
- name: SFTP-Server | Create directories per user
  file:
    path: "{{ sftp_home_partition }}/{{ item[0].name }}/{{ item[1].name | default(item[1]) }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].group | default(item[0].name) }}"
    mode: "{{ item[1].mode | default(0750) }}"
    state: directory
  with_subelements:
    - "{{ sftp_users }}"
    - "sftp_directories"
    - flags:
      skip_missing: True
