---
# vars file for mssql
mssql_gpgkey: https://packages.microsoft.com/keys/microsoft.asc

mssql_rhel_repositories:
  - name: packages-microsoft-com-mssql-server-2019
    description: Microsoft MSSQL server
    baseurl: https://packages.microsoft.com/rhel/7/mssql-server-2019/
  - name: packages-microsoft-com-prod
    description: Microsoft tools
    baseurl: https://packages.microsoft.com/rhel/7/prod/

mssql_ubuntu_repositories:
  - repo: https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/mssql-server-2019
  - repo: https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod

_mssql_server_package:
  Debian: mssql-server={{ mssql_server_version }}
  RedHat: mssql-server
  Suse: mssql-server-{{ mssql_server_version }}

mssql_server_package: "{{ _mssql_server_package[ansible_os_family] }}"

_mssql_server_agent_package:
  Debian: mssql-server-agent={{ mssql_server_agent_version }}
  RedHat: mssql-server-agent
  Suse: mssql-server-agent-{{ mssql_server_agent_version }}

mssql_server_agent_package: "{{ _mssql_server_agent_package[ansible_os_family] }}"

mssql_fts_package: mssql-server-fts






# defaults file for mssql

# mssql_add_repositories can be used to select if you want the repositories installed by this role.
# See vars/main.yml for the location of the repositories. Can be: yes, true or 1.
mssql_add_repositories: yes

# Select the version of server and server_agent to install.
mssql_server_version: 14.0.3223.3-15
mssql_server_agent_version: 14.0.3015.40-1

# mssql_sa_password contains the password for a system administrator.
# The password must be at least 8 characters long and contain characters from three of the following four sets:
# - uppercase letters
# - lowercase letters
# - numbers
# - and symbols
mssql_sa_password: "msPassword"

# mssql_pid refers to the product key to use. Either:
# - Evaluation
# - Developer
# - Express
# - Web
# - Standard
# - Enterprise
# - A product key (Format: #####-#####-#####-#####-#####)
mssql_pid: Evaluation

# To enable full text search, set this value to yes.
mssql_fts: no