- name: Install package PHP and etc.
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - httpd
    - policycoreutils-python 
    - php 
    - php-common 
    - php-gd 
    - php-mysql 
    - php-xml 
    - php-mbstring
    - nano 