---
- name: Install pkg with yum
  yum:
    name: ['python3-pip', 'ansible', 'libselinux-python', 'policycoreutils-python']
    state: present
    update_cache: true

- name: Upgrade pip
  shell: "pip install --upgrade pip"

- pip:
    name: 
      - docker
      - docker-compose
    executable: pip3

- name: Install AWX dependencies.
  package:
    name: "{{ loop_item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"
  loop_control:
    loop_var: loop_item
    
- name: Clone AWX into configured directory
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: true
    accept_hostkey: true

- name: Disable SELinux
  selinux:
    state: disabled

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ postgres_data_dir }}"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: false
