---
- name: add group
  group:
    name: "{{ kafka_group }}"
    state: present

- name: Add the user
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: "Download kafka binary package archive"
  get_url:
    url: "{{ kafka_url }}"
    dest: "{{ kafka_tmp_dir }}"
    use_proxy: yes
  environment:
    - http_proxy: '37.29.76.196:443'
  
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0755
  with_items:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

- name: "Extract downloaded kafka archive"
  unarchive: 
    copy: no 
    src: "{{ kafka_tmp_dir }}"
    dest: "{{ kafka_data_dir }}"
    extra_opts: [--strip-components=1]

- name: Copy config 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644 
    owner: root 
    group: root
  when: ansible_service_mgr == 'systemd'
  with_items:
    - { src: "zookeeper.service.j2",dest: "/etc/systemd/system/zookeeper.service" }
    - { src: "kafka.service.j2",dest: "/etc/systemd/system/kafka.service" }
    - { src: "kafka.j2",dest: "/etc/default/kafka" }

- name: "Reload systemctl daemon"
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: "Remove lost+found in the datadir"
  file: 
    path: "{{ kafka_data_dir }}/lost+found" 
    state: absent

- name: "Symlink kafka_conf_dir to data_dir/config"
  file: 
    src: "{{ kafka_data_dir }}"
    path: "{{ kafka_conf_dir }}"
    state: link
  notify:
    - restart zookeeper
    - restart kafka

- name: restart kafka
  systemd:
    state: "started"
    name: "kafka"
    daemon_reload: yes
    enabled: yes

