---
- name: copy Repo on remote server
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
    mode: u+rw,g-wx,o-rwx
  with_items:
  - remi-php73.repo
  - remi-safe.repo
  - mariadb.repo
  - zabbix.repo
  - altarix-epel7.repo
  register: zabbix_repo