---
- name: Remove old mount point from fstab in case of change
  lineinfile:
    dest: /etc/fstab
    regexp: "^/dev/{{ item.vg_name }}/{{ item.lv_name }} (?!.*{{ item.mount }} ).*"
    state: absent
  register: regex_fstab
  when: (item.pv_name in results.stdout )  # item exist in list
  with_items: "{{ disk_lvm }}"

- name: Unmount old mount point 
  mount:
    path: /dev/{{ item.vg_name }}/{{ item.lv_name }}
    state: unmounted
  when: item.pv_name in results.stdout  # item exist in list
  with_items: "{{ disk_lvm }}"

- name: Mount volume
  mount:
    name: "{{ item.mount }}"
    src: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
    fstype: "{{ item.filesystem | default ('xfs') }}"
    state: mounted
    opts: "{{ item.mount_options | default('defaults') }}"
  when: (item.pv_name in results.stdout )  # item exist in list
  with_items: "{{ disk_lvm }}"

- name: Ensure permissions mount
  file:
    path: "{{ item.mount }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: (item.pv_name in results.stdout )  # item exist in list
  with_items: "{{ disk_lvm }}"