# example for usage external network
version: '3.7'
services:
  lam:
    image: ldapaccountmanager/lam:stable
    container_name: lam
    networks:
      - iam_net
    ports:
      - 8080:80

networks:
  iam_net:
    external: true
