version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    restart: always
    environment:
      cluster.name: "elk"
      node.name: es01
      ELASTIC_PASSWORD: QWE123qwe
      ES_JAVA_OPTS: "-Xms12g -Xmx12g" # 50% of ram
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - "/data/efk_storage/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml" 
      - efk_data1:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /data/efk_storage/certs:/usr/share/elasticsearch/config/certificates
    expose:
      - 9200
    networks:
      - efk_stack

  fluentd:
    image: dockerregistry.company-vous.ru/devops/log-tools/efk/fluent:latest
    container_name: fluentd
    restart: always
    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    volumes:
      - /data/efk_storage/fluent/fluent.conf:/fluentd/etc/fluent.conf
      - /etc/localtime:/etc/localtime:ro
      - /data/efk_storage/certs:/certs
    networks:
      - efk_stack
        
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - "/data/efk_storage/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - /etc/localtime:/etc/localtime:ro
      - /data/efk_storage/certs:/usr/share/elasticsearch/config/certificates
    expose:
      - 5601
    networks:
      - efk_stack

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /data/efk_storage/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/efk_storage/nginx/htpasswd.efk:/etc/nginx/htpasswd.efk
      - /data/efk_storage/nginx/:/etc/nginx/ssl/
      - /etc/localtime:/etc/localtime:ro
      - /data/efk_storage/certs:/certs
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - efk_stack
      
volumes:
  efk_data1:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/efk_storage/es1'

networks:
  efk_stack:
#    driver: bridge
#env
#VERSION=7.10
#nano /etc/sysctl.conf
#vm.max_map_count = 262144
#sudo sysctl -p
# curl -X GET "localhost:9200/_cat/nodes?v&pretty"
