---
- name: copy tar on remote server
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
    mode: u+rw,g-wx,o-rwx
  with_items:
  - altarix-centos7.repo
  - altarix-centos7-updates.repo
  - altarix-epel7.repo
  - altarix-postgresql96.repo
  register: postgresql96_repo
