---
- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ PGDATA96 }}"
  when: 
  - not pg_version.stat.exists
  become: yes
  become_user: postgres
    #  See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
    #  vars:
    #    ansible_ssh_pipelining: true
    #  notify: restart postgresql

- name: Copy config
  template:
    src: "{{ line_item.src }}"
    dest: "{{ line_item.dest }}"
  with_items:
  - { src: "postgresql.service.j2",dest: "/etc/systemd/system/postgresql.service" }
  - { src: "postgres.sh.j2",dest: "/etc/profile.d/postgres.sh" }
  - { src: "postgresql.conf.j2",dest: "{{ PGDATA96 }}/postgresql.conf" }
  - { src: "pg_hba.conf.j2",dest: "{{ PGDATA96 }}/pg_hba.conf" }
  notify: restart postgresql
  loop_control: 
    loop_var: line_item

- debug:
    msg:  "{{ hostvars[line1_item]['ansible_default_ipv4']['network'] }}"
  with_items:
  - "{{ pg_network }}"
  loop_control: 
    loop_var: line1_item

- debug:
    msg:  "{{ pg_network }}"
  with_items:
  - "{{ pg_network }}"
  loop_control: 
    loop_var: line1_item


- name: Add trust in pg_hba.conf
  lineinfile:
    state: present
    dest: "{{ PGDATA96 }}/pg_hba.conf"
    regexp: 'host.*db.*{{ line1_item }}/32.*trust'
    line: "host    all    all  {{ hostvars[line1_item]['ansible_default_ipv4']['network'] }}/26 trust"
  with_items:
  - "{{ pg_network }}"
  notify: restart postgresql
  loop_control: 
    loop_var: line1_item
