---
- name: Delete pre-installed folders in webapps
  file:
    path: "{{ tomcat_webapps_path }}/{{ item.key }}/"
    state: absent
  with_dict: "{{ tomcat_pre_installed_folders_deployed }}"
  when: 'not item.value.deployed'

- name: Copy tomcat config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_items:
    - { src: "tomcat-users.xml.j2", dest: "{{ tomcat_conf_path }}/tomcat-users.xml" }
    - { src: "server.xml.j2", dest: "{{ tomcat_conf_path }}/server.xml" }
    - { src: "setenv.sh.j2", dest: "{{ tomcat_bin_path }}/setenv.sh" }
    - { src: "logging.properties.j2", dest: "{{ tomcat_conf_path }}/logging.properties" }
  notify: restart tomcat