# wildfly pkg
wildfly_version: "13.0.0.Final"
wildfly_package_name: "wildfly-{{ wildfly_version }}"
wildfly_package: "{{ wildfly_package_name }}.tar.gz"
wildfly_url: "http://download.jboss.org/wildfly/{{ wildfly_version }}/{{ wildfly_package }}"

# start on boot
wildfly_service_enabled: yes
# current state: started, stopped
wildfly_service_state: started

# Owner
wildfly_user: wildfly
wildfly_group: wildfly
wildfly_password: "$6$saltsalt$8OQ9OKxRmoALiFsM04dZ/UxD5T7fDG1PM//Paw3TNPIORTJKexWcM.qgMwEYVcjSXowprOE.djWBQO5zgdOyH1" #wildfly
wildfly_user_home: "/home/{{ wildfly_user }}"
wildfly_user_shell: "/bin/sh"
wildfly_user_uid: 1005
# Management
wildfly_management_users:
  - name: "wildfly"
    password: "wildfly"

# Files & Paths
wildfly_conf_path: "/etc/wildfly"
wildfly_install_path: "/usr/share"
wildfly_home_path: "{{ wildfly_install_path }}/wildfly"
wildfly_log_file_path: "{{ wildfly_home_path }}/standalone/log"
wildfly_running_configuration_file: "{{ wildfly_home_path }}/bin/standalone.conf"

# Log
wildfly_log_file_name: server.log
wildfly_log_console_enabled: "false"
wildfly_log_console_level: DEBUG
wildfly_log_file_enabled: "true"
wildfly_log_file_level: DEBUG
wildfly_log_file_rotatesize: 1024000
wildfly_log_file_maxBackupIndex: 7

# Network
wildfly_bind: "{{ansible_default_ipv4.address}}"
wildfly_port: "9990"
#wildfly_bind: 0.0.0.0
wildfly_bind_xml: "{{ansible_default_ipv4.address}}"
#FOR DEPLOY
project_folder: "serverside-develop"
project_tar: "{{project_folder}}.tar.gz"

gradle_home: "/usr/share/gradle/bin"
