---
- name: status firewalld
  service:      
    name: firewalld
  register: services_state

- name: Allow service in firewalld
  firewalld: 
    service: "samba"
    permanent: true 
    state: enabled 
    immediate: yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'running' or services_state.status.ActiveState == 'active'