---
- name: add-repo
  include: add-repo.yml

- name: install
  include: install.yml

#- name: firewall.yml
#  include: firewall.yml

- name: config
  include: config.yml

- include: domain_users.yml
  when: >
    samba_create_domain_users is defined and
    samba_create_domain_users and
    samba_domain_controllers_group is defined
#   inventory_hostname == samba_primary_domain_controller

- include: domain_groups.yml
  when: >
    samba_create_domain_groups is defined and
    samba_create_domain_groups and
    samba_domain_controllers_group is defined
#   inventory_hostname == samba_primary_domain_controller

