version: '3'
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - /var/www/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    networks:
      - nextcloud_network

  app:
    container_name: nextcloud
    image: nextcloud:latest
    ports:
      - 8081:80
    volumes:
      - /var/www/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USERL:'nextcloud'
      - NEXTCLOUD_ADMIN_PASSWORD:'QWE123qwe'
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
#   env_file:
#      - db.env
#    links:
#      - db
    depends_on:
      - db
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
