---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

- name: Open 8080/9900 port in firewalld
  firewalld: 
    port={{item}}
    permanent=true 
    state=enabled 
    immediate=yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'running'
  with_items:
  - 8080/tcp
  - 9990/tcp


