---
- name: Creates directory - mongo_data
  file:
    path: "{{dir_for_mongo_data}}"
    state: directory
    owner: "mongod"
    group: "mongod"
    mode: 0775
    
- name: Creates directory - es_data
  file:
    path: "{{dir_for_es_data}}"
    state: directory
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0775
    
- name: Creates directory - dir_for_graylog
  file:
    path: "{{dir_for_graylog}}"
    state: directory
    owner: "graylog"
    group: "graylog"
    mode: 0775

- name: mongodb should be configured
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
  notify: "restart mongo"

- name: copy all files from 1 dir to another GRAYLOG
  copy:
    src: "{{ item }}"
    dest: "{{ dir_for_graylog }}/"
#    owner: root
#    mode: 600
  with_fileglob:
    - /usr/share/graylog-server/*

- name: copy all files from 1 dir to another ELASTIC
  copy:
    src: "{{ item }}"
    dest: "{{ dir_for_es_data }}/"
#    owner: root
#    mode: 600
  with_fileglob:
    - /usr/share/elasticsearch/*

- name: elasticsearch should be configured
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0644
  notify: "restart elasticsearch"

- name: Directory should be created with correct ownership and privileges
  file:
    path: "/etc/graylog/server"
    owner: "graylog"
    group: "graylog"
    mode: 0750

- name: Graylog server should be configured
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"
