variables:
   REGISTRY_BASE_URL: registry.docker.company.org:5001/gilmullinrr/ansible-roles/ansible

#  GIT_STRATEGY: none
#image: docker:git
#services:
#    - docker:dind
  
stages:
- build
- vmcreating
- infra2

build:
  stage: build
  - docker build --tag="$REGISTRY_BASE_URL:$CI_JOB_NAME" -f build/Dockerfile .
  - docker login -u gitlab-ci-token -p $token $REGISTRY_BASE_URL
  - docker push $REGISTRY_BASE_URL:$CI_JOB_NAME
  tags: 
    - docker
  only: 
    - master
  when: manual


#infra:
#  image: 
#    name: $REGISTRY_BASE_URL:latest
#  stage: infra
#  before_script:
#  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client python-crypto -y )'
#  - eval $(ssh-agent -s)
#  - mkdir -p ~/.ssh/
#  - chmod -R 700 ~/.ssh/
#  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
##  - export ANSIBLE_HOST_KEY_CHECKING=False
#  script:
#  - ansible -i hosts 127.0.0.1 -u ${PREROLE_USERNAME} -m ping 
#  - ansible-playbook main.yml -i hosts -u ${PREROLE_USERNAME}
#  - ansible -i hosts asupr -u ${PREROLE_USERNAME} -m ping 
   #--extra-vars "ansible_ssh_pass='DEoG4gsW'"
   #"ansible_sudo_pass=debtest" ansible_ssh_pass='DEoG4gsW'
#  - ansible-playbook main.yml -i hosts -u ${user}
#  - ansible -i hosts all -u $USERNAME -m ping
#  - ansible-playbook main.yml -i hosts -u $USERNAME --tags "php"
#  - ansible -i hosts all -u $USERNAME_prerole -m ping --extra-vars "ansible_ssh_pass=debtest"
#  - ansible-playbook -i hosts main.yml -u gilmullinrr --extra-vars "ansible_ssh_pass=RR8989ok"
#  tags:
#  - mydocker
#  - docker_MONM_172_24_52_5
#  only:
#  - master
#  when: manual


vmcreating:
  stage: vmcreating
  image: 
    name: $REGISTRY_BASE_URL:latest
  before_script:
  - pip install pyvmomi pynetbox==4.3.3
  - 'which ssh-agent || ( apk add --update openssh )'
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh/
  - chmod -R 700 ~/.ssh/
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
  - echo $vault_pass > secret
#  - chmod 600 id_rsa
#  - export ANSIBLE_HOST_KEY_CHECKING=False
#  - ssh -o StrictHostKeyChecking=no -i id_rsa -v ansible_user@172.29.27.36 echo test
#  - ansible -i hosts -u ansible_user -m ping athena --vault-password-file=secret
  - ansible-playbook -i hosts -u ansible_user main.yml --vault-password-file=secret
  tags:
  - docker
  only:
  - master
  when: manual


# alpine
infra2:
  image: 
    name: $REGISTRY_BASE_URL:latest
  stage: infra2
  before_script:
  - export PATH=${PATH}:/usr/bin/python3
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "$SSH_KEY_VMS")'
  - mkdir ~/.ssh
  - chmod -R 700 ~/.ssh/
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
#  - ansible -i hosts 10.250.88.201 -u ${PREROLE_USERNAME} -m ping 
#  - ansible-playbook -i hosts -u ansible_user main.yml -i hosts #--tags "test1"
  - ansible-playbook -i hosts -u gilmullinrr main.yml -i hosts
  tags:
  - docker
#  - mydocker2
  only:
  - master
  when: manual
