- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  become: true
  connection: local
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"
  roles:
    - pre_role

- name: MAIN
  hosts: all
  become: true
  vars_files:       # path to ansible-vault pass
    - roles/pre_role/files/secret
  tasks:    
    - name: test
      command: "echo start copy public key on all server in hosts"

    - name: Create user
      user:
        name: "{{ item.username }}"
 #       password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        append: "yes"
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: "/home/{{ item.username }}"
      when: 'item.username != ""'
      with_items: 
        - "{{ deploy_ansible }}"
      ignore_errors: yes 
      no_log: true

    - name: Set authorized keys taken from url
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.pub_key }}"
      no_log: true
      with_items: 
        - "{{ deploy_ansible }}"

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
