---
- name: SFTP-Server | Create dev directory for logging
  file:
    path: "{{ sftp_home_partition }}/{{ item.name }}/dev"
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ sftp_users }}"
  when: sftp_enable_logging

- name: SFTP-Server | Enable Logging
  blockinfile:
    dest: "/etc/rsyslog.d/sshd.conf"
    create: yes
    block: |
      # Create an additional socket for some of the sshd chrooted users.
      {% for user in sftp_users %}
      $AddUnixListenSocket {{ sftp_home_partition }}/{{ user.name }}/dev/log
      {% endfor %}
      # Log internal-sftp in a separate file
      :programname, isequal, "internal-sftp" -/var/log/sftp/verbose.log
      :programname, isequal, "internal-sftp" ~
      # additionally write an auth log
      auth,authpriv.*  /var/log/sftp/auth.log
  when: sftp_enable_logging
  notify: Restart rsyslog
