---
- name: "Check if DOCKER is installed"
  package_facts:
    manager: "auto"

- name: MAIN | include role Docker
  include_role:
    name: docker
  when: "'docker-ce' not in ansible_facts.packages"
 
- name: MAIN | add-repo
  include_tasks: add-repo.yml

- name: MAIN | pre_install
  include_tasks: pre_install.yml

- name: MAIN | firewall
  include_tasks: firewall.yml

- name: MAIN | install
  include_tasks: install.yml

- name: MAIN | Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kube_init_stat

- name: MAIN | REMOVE cluster and old kube
  include_tasks: "remove.yml"
  when: (remove == true)

- name: MAIN | Check if Kubernetes has already been initialized.
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: MAIN | master
  include_tasks: master.yml
  when: 
  - (ansible_default_ipv4.address == item.ip and item.name == 'master')
#  -  not kube_init_stat.stat.exists
  with_items: "{{ entries }}"
#  run_once: yes
  register: result_master

- name: MAIN | slave 
  include: slave.yml
  when: (ansible_default_ipv4.address == item.ip and 'slave' in item.name and item.name != 'master' and result_master is succeeded)
  with_items: "{{ entries }}"

- name: MAIN | Show url for dashboard
  debug:
    msg: "http://{{item.ip}}:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login"
  when: 
  - (ansible_default_ipv4.address == item.ip and item.name == 'master')
  with_items: "{{ entries }}"
