---
- name: Disable swap
  command: "swapoff -a"

# solution for - /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
- name: PRE | Add the br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: PRE | ensure net.bridge.bridge-nf-call-iptables and net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: "{{item}}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: PRE | Add the inventory into /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  with_items:
    - "{{ entries }}"

#- name: Add mappings to /etc/hosts
#  blockinfile:
#    path: /etc/hosts
#    block: |
#      {{ item.ip }} {{ item.name }}
#    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
#  with_items:
#    - "{{ entries }}"

- name: Create user
  user:
    name: "{{ kube_user }}"
    password: "{{ kube_pass }}"
    groups:
    - wheel
    - docker
    append: yes
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/{{ kube_user }}
  when: create_user | bool
  ignore_errors: yes
