version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/efk_storage/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml" 
      - /data/efk_storage/elasticsearch:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - efk_stack

  fluentd:
    image: registry.docker.test.org:5001/test/test-serverside/fluent:remaster
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    volumes:
      - /data/efk_storage/fluent/fluent.conf:/fluentd/etc/fluent.conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      - efk_stack
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    volumes:
      - "/data/efk_storage/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "5601:5601"
    networks:
      - efk_stack

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /data/efk_storage/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/efk_storage/nginx/htpasswd.efk:/etc/nginx/htpasswd.efk
      - /data/efk_storage/nginx/proxy.conf:/etc/nginx/proxy.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 8080:8080
    networks:
      - efk_stack

networks:
  efk_stack:
    external: true
