version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - /data/prometheus_storage/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
#    ports:
#      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - prom-stack
    restart: always


  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    command:
      - '--config.file=/config/blackbox.yml'
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    volumes:
      - /data/prometheus_storage/blackbox:/config
#    ports:
#      - 9115:9115
    networks:
      - prom-stack


    
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
#    ports:
#      - 9093:9093
    volumes:
      - /data/prometheus_storage/alertmanager/:/etc/alertmanager/
    networks:
      - prom-stack
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472"
    restart: unless-stopped
    depends_on:
      - prometheus
#    ports:
#      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /data/prometheus_storage/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /data/prometheus_storage/grafana/config.monitoring
    networks:
      - prom-stack
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - /data/prometheus_storage/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/prometheus_storage/nginx/htpasswd.efk:/etc/nginx/htpasswd.efk
      - /data/prometheus_storage/nginx/proxy.conf:/etc/nginx/proxy.conf
    depends_on:
      - prometheus
      - grafana
    ports:
      - 80:80
      - 8080:8080
    networks:
      - prom-stack

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/prometheus_storage/prometheus'
  grafana_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/prometheus_storage/grafana'

networks:
  prom-stack:
    external: true
