global:
  # How frequently to scrape targets
  scrape_interval:     10s
  # How frequently to evaluate rules
  evaluation_interval: 10s
  external_labels:
    monitor: 'PROMETHEUS' # label for slack alerts

rule_files:
  - 'alert.rules'
  - "containers_rules.yml"
  
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - '172.105.159.75:8019'

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - '172.105.159.75:8016'
      labels:
        instance: 'node'
          
  - job_name: 'nginx'
    static_configs:
    - targets:
      - '11.111.11.11:9113'
      - '11.111.11.12:9113'
      
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets:
       - https://confluence.company.com
       labels:
         instance: 'API DEV'
     - targets:
       - https://jira.company.com
       - https://jiratest.company.com
       labels:
         instance: 'JIRA'
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115
#    file_sd_configs:
#    - files:
#      - scrape/blackbox/*.yml   #путь указан из папки прометеуса
