---
#- name: restart elasticsearch
#  service:
#    name: elasticsearch
#    state: restarted
#    enabled: yes

#- name: restart kibana
#  service:
#    name: kibana
#    state: restarted
#    enabled: yes

- name: restart elastic
  systemd:
    state: restarted
    daemon_reload: yes
    name: elasticsearch
    enabled: yes

- name: restart kibana
  systemd:
    state: restarted
    daemon_reload: yes
    name: kibana
    enabled: yes
