---
- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: Connect to Gluster peers.
  shell: "gluster peer probe {{groups['GLUSTER_SERVER'][0]}}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  failed_when: false
  when: (item not in gluster_volume_info.stdout)
  with_items: "{{name_gluster_vlm}}"

- name: create gluster volume
  gluster_volume:
    state: present
    name: "{{name_gluster_vlm}}"
    bricks: "{{dir_for_gluster}}"
    replicas: "{{replicas}}"
    force: true #true if in root partition
    cluster: "{{groups['GLUSTER_SERVER'] | join(',') }}"
  when: (item not in gluster_volume_info.stdout)
  run_once: true  
  ignore_errors: true
  with_items: "{{name_gluster_vlm}}"
