---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

#need test
- name: Set firewall
  command: firewall-cmd --zone=public --add-service=nfs --add-service=samba --add-service=samba-client --permanent
  ignore_errors: yes   
  when: services_state.ansible_facts.services["firewalld.service"].state == 'running'

- name: Open port in firewalld
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'running'
  with_items:
    - 24007-24009/tcp
    - 111/tcp
    - 139/tcp
    - 445/tcp
    - 965/tcp
    - 2049/tcp
    - 38465-38469/tcp
    - 631/tcp
    - 49152-49251/tcp
    - 111/udp
    - 963/udp
