---
# task file for mysql
- name: "Set the correct delegated_dbhost (to support MySQL db deployment on a remote dbhost)"
  set_fact:
    delegated_dbhost: "{{ zabbix_server_dbhost if (zabbix_server_dbhost != 'localhost') else inventory_hostname}}"

- name: "MySQL | Create database"
  mysql_db:
    name: "{{ zabbix_server_dbname }}"
    encoding: "{{ zabbix_server_dbencoding }}"
    collation: "{{ zabbix_server_dbcollation }}"
    login_host: "{{ zabbix_server_mysql_login_host | default(omit) }}"
    login_user: "{{ zabbix_server_mysql_login_user | default(omit) }}"
    login_password: "{{ zabbix_server_mysql_login_password | default(omit) }}"
    login_port: "{{ zabbix_server_mysql_login_port | default(omit) }}"
    login_unix_socket: "{{ zabbix_server_mysql_login_unix_socket | default(omit) }}"
    state: present
  when: zabbix_database_creation
  register: zabbix_database_created
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database
    - skip_ansible_lint

- name: "MySQL | Create database user"
  mysql_user:
    login_host: "{{ zabbix_server_mysql_login_host | default(omit) }}"
    login_user: "{{ zabbix_server_mysql_login_user | default(omit) }}"
    login_password: "{{ zabbix_server_mysql_login_password | default(omit) }}"
    login_port: "{{ zabbix_server_mysql_login_port | default(omit) }}"
    login_unix_socket: "{{ zabbix_server_mysql_login_unix_socket | default(omit) }}"
    name: "{{ zabbix_server_dbuser }}"
    password: "{{ zabbix_server_dbpassword }}"
    priv: "{{ zabbix_server_dbname }}.*:ALL"
    state: present
  when: zabbix_database_creation
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database

- name: "Get the file for create.sql"
  shell: "ls -1 {{ datafiles_path }}"
  changed_when: False
  when:
    - zabbix_database_sqlload
  register: ls_output_create
  tags:
    - zabbix-server
    - database

- name: "Check if we have done files"
  stat:
    path: /etc/zabbix/create.done
  register: done_file
  when:
    - zabbix_database_sqlload

- name: "MySQL | Create database and import file"
  mysql_db:
    login_host: "{{ zabbix_server_mysql_login_host | default(omit) }}"
    login_user: "{{ zabbix_server_mysql_login_user | default(omit) }}"
    login_password: "{{ zabbix_server_mysql_login_password | default(omit) }}"
    login_port: "{{ zabbix_server_mysql_login_port | default(omit) }}"
    login_unix_socket: "{{ zabbix_server_mysql_login_unix_socket | default(omit) }}"
    name: "{{ zabbix_server_dbname }}"
    encoding: "{{ zabbix_server_dbencoding }}"
    collation: "{{ zabbix_server_dbcollation }}"
    state: import
    target: "{{ ls_output_create.stdout }}"
  when:
    - zabbix_database_sqlload
    - not done_file.stat.exists
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database

- name: "Check if we have sql_done files"
  file:
    path: /etc/zabbix/create.done
    state: touch
  when:
    - zabbix_database_sqlload
    - not done_file.stat.exists