---
variables:
  SSH_CONFIG: "-o StrictHostKeyChecking=no"
  CI_REGISTRY_USER: "gitlab+deploy-token-52"
  CI_REGISTRY_PASSWORD: $token
  CI_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}
  DOCKER_LOGIN: "docker login -u gitlab-ci-token -p $token ${CI_REGISTRY}"

stages:
  - build
  - deploy

.build-buildkit:
  stage: build
  image:
    name: moby/buildkit:master
    entrypoint: [ "sh", "-c" ]
  script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 )\"}}}" > ~/.docker/config.json
    - |
      buildctl-daemonless.sh build \
      --frontend=dockerfile.v0 \
      --local context=${CI_PROJECT_DIR} \
      --local dockerfile=${CI_PROJECT_DIR}/${APP_DOCKERFILE} \
      --export-cache type=registry,ref=${CI_IMAGE}:buildcache,push=true \
      --import-cache type=registry,ref=${CI_IMAGE}:buildcache,push=true \
      --output type=image,name=${CI_IMAGE}:${CI_COMMIT_REF_NAME},push=true \
      --opt build-arg:APP_PATH=$APP_DOCKERFILE
  tags:
    - docker

.build-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
        /kaniko/executor \
          --context $CI_PROJECT_DIR \
          --cache \
          --cache-repo ${CI_IMAGE} \
          --dockerfile $CI_PROJECT_DIR/${APP_DOCKERFILE}/Dockerfile \
          --destination ${CI_IMAGE}:${CI_COMMIT_REF_NAME} \
          --build-arg APP_PATH=$APP_DOCKERFILE
  tags:
    - docker

.deploy:
  stage: deploy
  when: manual

lightbox-filesync:
  extends: .build-buildkit
  variables:
    APP_DOCKERFILE: "k8s/images/file-sync" 

