---
- name: "join as a worker"
  shell: "docker swarm join --token {{ hostvars[line4_item]['worker_token']['stdout'] }} {{ hostvars[line4_item]['ansible_default_ipv4']['address'] }}:2377"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"
  retries: 3
  delay: 20
  with_items: 
  - "{{ groups['manager_first'][0] }}"
  loop_control:
    loop_var: line4_item
