---
- name: MAIN | add-repo
  include: add-repo.yml
  
- name: MAIN | install
  include: install.yml

- name: MAIN | firewall
  include: firewall.yml

- name: MAIN | master
  include: master.yml
  when: (ansible_default_ipv4.address == hostvars[item]['ansible_default_ipv4']['address'])
  with_items: 
  - "{{ master_ip }}"

- name: MAIN | replica start
  include: replica.yml
  when: (ansible_default_ipv4.address == hostvars[item]['ansible_default_ipv4']['address'])
  with_items: 
  - "{{ slave_ip }}"

- name: MAIN | check sync_state
  include: check_sync.yml
  when: (ansible_default_ipv4.address == hostvars[item]['ansible_default_ipv4']['address'])
  with_items: 
  - "{{ master_ip }}"

- name: MAIN | Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"




