- name: For each host, scan for its ssh public key
  shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
  with_items: "{{ ssh_known_hosts| lower }}"
  register: ssh_known_host_results
  ignore_errors: yes

- name: Add/update known_hosts in the '{{ ssh_known_hosts_file }}' on localhost
  known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    path: "{{ ssh_known_hosts_file }}"
  with_items: "{{ ssh_known_host_results.results }}"
  no_log: true
  ignore_errors: yes

- name: Install package sshpass and etc.
  package: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - sshpass
    - nano
    - squid
  become: true
  ignore_errors: yes
  environment: "{{item}}"
  with_items: "{{proxy_env}}"