---


- name: Install repo postgres
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages: 
      - "https://download.postgresql.org/pub/repos/yum/{{major_ver}}/redhat/rhel-7-x86_64/pgdg-centos{{major_ver}}-{{major_ver}}-{{minor_ver}}.noarch.rpm"
  environment: "{{item}}"
  with_items: "{{proxy_env}}"
