---
- name: "confirm service exists"
  stat: 
    path: /etc/init.d/docker
  register: service_wrapper

- name: "Check whether api already exposed"
  command: "grep 'DOCKER_OPTS=\"-D -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\"' /etc/docker/daemon.json"
  register: check_has_api
  check_mode: yes
  ignore_errors: True
  changed_when: False

- name: "Stop Docker"
  service: name=docker state=stopped
  when:
    - service_wrapper.stat.exists
    - check_has_api.stdout == ""
  register: service_stopped

- name: "expose docker api"
  lineinfile: 
    dest: /etc/default/docker
    state: present 
    regexp: '#DOCKER_OPTS=' 
    line: 'DOCKER_OPTS=\"-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\"'
  when:
    - service_stopped
    - check_has_api.stdout == ""

- name: "Restart Docker service"
  service: name=docker state=started
  when:
    - service_wrapper.stat.exists
    - check_has_api.stdout == ""