---
- name: Install rabbitmq and etc.
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - erlang
    - rabbitmq-server
#    - socat
    - bash-completion
    - bash-completion-extras
  when: epel7_repo is success
  environment: "{{item}}"
  with_items: "{{proxy_env}}"
  notify: restart rabbitmq
  register: rabbitmq_installed

- name: copy packages rabbitmq on remote server
  copy:
    src: "{{ item }}"
    dest: "/tmp"
    mode: 0755
  with_items:
  - "erlang-21.2.6-1.el7.x86_64.rpm"
  - "rabbitmq-server-3.7.13-1.el7.noarch.rpm"

#- name: Install package rabbitmq
#  yum:
#    name: 
#      - "/tmp/erlang-21.2.6-1.el7.x86_64.rpm"
#      - "/tmp/rabbitmq-server-3.7.13-1.el7.noarch.rpm"
#    state: present
#  notify: restart clickhouse_server
  
- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  when: rabbitmq_installed is success
  notify: restart rabbitmq

- name: chown rabbitmq_management
  file: 
    dest=/var/lib/rabbitmq/ 
    owner=rabbitmq
    group=rabbitmq
    recurse=yes
  when: rabbitmq_installed is success
  notify: restart rabbitmq

- name: restart rabbitmq
  service:
    name: "rabbitmq-server"
    state: restarted
    enabled: yes

- name: for restart
  local_action: command whoami
  notify: restart rabbitmq
  when: rabbitmq_installed is success
