---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

- name: Open port in firewalld
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  when: services_state.status.ActiveState == 'running'
  ignore_errors: yes
  with_items:
    - "http"
    - "https"
