version: '3.6'
services:
  confluence:
    container_name: confluence
    image: docker.io/atlassian/confluence-server:7.8.3
    restart: unless-stopped
    hostname: confluence
    depends_on:
      - "confluence-db"
    environment:
      JVM_MINIMUM_MEMORY: 2048
      JVM_MAXIMUM_MEMORY: 2048
      JVM_SUPPORT_RECOMMENDED_ARGS: -Xmx4056M -Xms4056M
      CATALINA_CONNECTOR_PROXYNAME: confluence.company.ru
      CATALINA_CONNECTOR_PROXYPORT: 443
      CATALINA_CONNECTOR_SCHEME: https
      CATALINA_CONNECTOR_SECURE: "True"
    volumes:
      - ./confluence:/var/atlassian/application-data/confluence
      - ./server.xml:/opt/atlassian/confluence/conf/server.xml
    ports:
      - 8090:8090
      - 8091:8091
    network_mode: "bridge"

  confluence-db:
    container_name: confluence-db
    image: postgres:12
    restart: unless-stopped
    hostname: postgresql-confluence
    environment:
      POSTGRESQL_USER: confluence
      POSTGRESQL_PASSWORD: confluencepasswd
      POSTGRESQL_DATABASE: confluence
      POSTGRESQL_ADMIN_PASSWORD: confluencepasswdadmin
    volumes:
      - ./db:/var/lib/pgsql/data
    network_mode: "bridge"
