---
- name: Add RabbitMQ users
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: "/"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
    tags: "administrator"
    state: present

