---
- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host
  become: false

- name: Creates directory gluster
  file:
    path: "{{dir_for_gluster}}"
    state: directory
    owner: '{{ username_on_the_host.stdout }}'
    group: '{{ username_on_the_host.stdout }}'
    mode: 0775

- name: install gluster-server
  package:
    name: glusterfs-server
    state: present
  when: gluster_repo is success
  environment: "{{item}}"
  with_items: "{{proxy_env}}"
  notify: start glusterd