---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

- debug:
    msg: "{{services_state.status.ActiveState}}"

- name: Open port in firewalld
  firewalld:
    port: "{{item}}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'active' or services_state.status.ActiveState == 'running'
  with_items:
  - 8080