---

- name: Install package nodejs
  package:
    name: "{{ packages }}"
    state: present
  vars: 
    packages:
      - nodejs
  environment: "{{item}}"
  with_items: "{{proxy_env}}"

- name: copy on remote server 1
  copy:
    src: "pm2-3.3.1.tgz"
    dest: "/tmp/pm2-3.3.1.tgz"

- name: copy on remote server 2 
  copy:
    src: "pm2.npmbox"
    dest: "/tmp/pm2.npmbox"

- name: copy on remote server 3
  copy:
    src: "npmbox.npmbox"
    dest: "/tmp/npmbox.npmbox"

- name: copy on remote server 4
  copy:
    src: "pm2-logrotate.npmbox"
    dest: "/tmp/pm2-logrotate.npmbox"

- name: Install npmbox from tar
  command: "tar --no-same-owner --no-same-permissions -xvzf /tmp/npmbox.npmbox"
  args:
    warn: false

- name: Install npmbox
  command: "npm install --global --cache ./.npmbox.cache --optional --cache-min 99999999999 --shrinkwrap false npmbox"
- name: Install pm2 from npmbox
  command: "npmunbox /tmp/pm2.npmbox --global"

#- name: Install pm2 with npm
#  npm:
#    name: pm2
#    global: yes
#    version: "{{ pm2_version | default(omit) }}"
#  notify: update pm2

- name: Looking up user home
  shell: >
    egrep "^{{ pm2_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Install pm2-logrotate from npmbox
  command: "npmunbox /tmp/pm2-logrotate.npmbox --global"

- name: Installing startup script
  command: "pm2 startup {{ pm2_platform }} -u {{ pm2_user }} --hp {{ pm2_user_home.stdout }}"
  when: pm2_upstart