version: '3.8'
services:
  fluentd:
    image: registry.company.com/fluent/fluent:1
    ports:
      - 8020:8020
    environment:
      - env=${env}
      - collector_ip=${collector_ip}
    user: root
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    volumes:
      - /data/fluentd_client:/data 
      - /data/docker/containers:/logs/docker_logs:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app_network

networks:
  app_network:
    external: true
