version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/efk_storage/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml" 
      - efk_data1:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9200
    networks:
      - efk_stack

# logstash:
#   image: docker.elastic.co/logstash/logstash:7.8.1
#   container_name: logstash
#   environment:
#     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#   ports:
#     - "5000:5000"
#     - "9600:9600"
#   volumes:
#     - "/data/efk_storage/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:rw"
#   networks:
#     - efk_stack

  fluentd:
    image: registry.shakticoin.com/fluent/fluent:1
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    volumes:
      - /data/efk_storage/fluent/fluent.conf:/fluentd/etc/fluent.conf
      - /etc/localtime:/etc/localtime:ro
    networks:
      - efk_stack
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    volumes:
      - "/data/efk_storage/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 5601
    networks:
      - efk_stack

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /data/efk_storage/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/efk_storage/nginx/htpasswd.efk:/etc/nginx/htpasswd.efk
      - /data/efk_storage/nginx/proxy.conf:/etc/nginx/proxy.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 8080:8080
    networks:
      - efk_stack
      
volumes:
  efk_data1:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/efk_storage/es1'

networks:
  efk_stack:
    external: true
#    driver: bridge
#env
#VERSION=7.8.1
#nano /etc/sysctl.conf
#vm.max_map_count = 262144
#sudo sysctl -p
# curl -X GET "localhost:9200/_cat/nodes?v&pretty"