---
- name: Configure java Xms option
  lineinfile:
          path: /etc/elasticsearch/jvm.options
          regexp: '^-Xms2g'
          line: '-Xms{{ java_memory }}'

- name: Configure java Xmx option
  lineinfile:
          path: /etc/elasticsearch/jvm.options
          regexp: '^-Xmx2g'
          line: '-Xmx{{ java_memory }}'

- name: elasticsearch should be configured
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0644
  notify: "restart elastic"

- name: Copy config kibana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: "kibana.yml.j2",dest: "/etc/kibana/kibana.yml" }
  notify: restart kibana
