---
## Owner
tomcat_group: "tomcat"
tomcat_user: "tomcat"

## INSTALL

#Company
tomcat_url: "https://upload.company.org/apache-tomcat-9.0.13.tar.gz"
#tomcat_url: "http://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

tomcat_version: "9.0.13"
tomcat_package: "apache-tomcat-{{ tomcat_version }}.tar.gz"
## Miscellaneous
tomcat_force_reinstall: false

## Files & Paths
tomcat_logs_path: "/var/log/tomcat"
tomcat_install_path: "/opt/tomcat"
tomcat_bin_path: "{{ tomcat_install_path }}/bin"
tomcat_conf_path: "{{ tomcat_install_path }}/conf"
tomcat_webapps_path: "{{ tomcat_install_path }}/webapps"

## Service options
tomcat_service_enabled: yes
tomcat_service_state: started

# CONFIG
tomcat_pre_installed_folders_deployed:
  docs:
    deployed: true
  examples:
    deployed: true
  manager:
    deployed: true
  host-manager:
    deployed: true
  ROOT:
    deployed: true


###############################################################
#TEMPLATE:
###############################################################

# tomcat-users.xml.j2
###############################################################
tomcat_roles:
  - manager-gui

tomcat_users:
  - name: admin
    password: must-be-changed
    roles: manager-gui

## server.xml.j2
###############################################################
## Ports
tomcat_shutdown_port: 8005
tomcat_shutdown_command: SHUTDOWN
tomcat_http_connector_port: 8080
tomcat_http_connector_connection_timeout: 20000
tomcat_ajp_connector_port: 8009
tomcat_connector_redirect_port: 8443

## setenv.sh.j2
###############################################################
tomcat_environment_vars:
  - name: UMASK
    value: "\"0022\""

## CATALINA_OPTS
tomcat_catalina_opts:
  - -Xms512m
  - -Xmx512m


#logging.properties.j2
###############################################################

## Logs path (optional, by default its used tomcat_default_log_catalina_out, tomcat_default_log_logging_path and tomcat_default_log_valves)
# tomcat_logs_path: /var/log/tomcat
tomcat_logs_level: {
  juli: FINE,
  catalina: INFO
}

tomcat_default_log_catalina_out: '"$CATALINA_BASE"/logs'
tomcat_default_log_logging_path: "${catalina.base}/logs"
tomcat_default_log_valves: "logs"



