---
- name: Install package
  yum:
    name: "{{ redis_package }}"
    state: present
  environment: "{{item}}"
  with_items: "{{proxy_env}}"

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis
