---
- name: Install package
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-setuptools
    - supervisor
  when: supervisor_repo is success
  environment: "{{item}}"
  with_items: "{{proxy_env}}"
