variables:
   REGISTRY_BASE_URL: registry.docker.company.org:5001/ansible-roles/ansible

stages:
- build
- vmcreating
- infra

build:
  stage: build
  - docker build --tag="$REGISTRY_BASE_URL:$CI_JOB_NAME" -f build/Dockerfile .
  - docker login -u gitlab-ci-token -p $token $REGISTRY_BASE_URL
  - docker push $REGISTRY_BASE_URL:$CI_JOB_NAME
  tags: 
    - docker
  only: 
    - master
  when: manual


vmcreating:
  stage: vmcreating
  image: 
    name: $REGISTRY_BASE_URL:latest
  before_script:
  - pip install pyvmomi pynetbox==4.3.3
  - 'which ssh-agent || ( apk add --update openssh )'
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh/
  - chmod -R 700 ~/.ssh/
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
  - echo $vault_pass > secret
  - ansible-playbook -i hosts -u ansible_user main.yml --vault-password-file=secret
  tags:
  - docker
  only:
  - master
  when: manual

infra:
  image: 
    name: $REGISTRY_BASE_URL:latest
  stage: infra
  before_script:
  - export PATH=${PATH}:/usr/bin/python3
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "$SSH_KEY_VMS")'
  - mkdir ~/.ssh
  - chmod -R 700 ~/.ssh/
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
  #- ansible -i hosts 10.250.88.201 -u ${PREROLE_USERNAME} -m ping 
  - ansible-playbook -i hosts -u ${PREROLE_USERNAME} main.yml -i hosts #--tags "test1"
  tags:
  - docker
  only:
  - master
  when: manual
