---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

- name: Open http port in firewalld
  firewalld: 
    port: "{{item}}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'running'
  with_items:
  - "http/tcp"
  - "{{ httpd_listen }}"
  - "{{ httpd_listen_ssl }}"


- name: "SELinux port access should be granted"
  command: "setsebool -P httpd_can_network_connect 1"
  ignore_errors: yes
  when: ansible_selinux.status == 'enabled'
