---
- name: check Active Directory setup
  stat: path=/etc/samba/smb.conf
  register: samba_setup_check

- name: set Active Directory
  command: "/usr/bin/samba-tool domain provision {{ config_domain }}"

- name: Copy config service and krb5
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "samba.service.j2",dest: "/etc/systemd/system/samba.service" }
    - { src: "/usr/var/lib/samba/private/krb5.conf",dest: "/etc/krb5.conf" }

- name: Copy config named
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "named"
  with_items:
    - { src: "named.conf.j2 ",dest: "{{ bind_config }}" }

