---
- name: status firewalld
  service:      
    name: firewalld
  register: services_state

- name: Open port in firewalld
  firewalld: 
    port: "{{item}}/tcp"
    permanent: true 
    state: enabled 
    immediate: yes
  ignore_errors: yes
  when: services_state.status.ActiveState == 'running' or services_state.status.ActiveState == 'active'
  with_items:
  - 5432

- name: "SELinux port access should be granted"
  seport:
    ports: "{{ item }}"
    proto: "tcp"
    setype: "postgresql_port_t"
    state: "present"
  ignore_errors: yes
  with_items:
    - 5432
  when: ansible_selinux.status == 'enabled'