---
- name: status service firewalld
  service:
    name: firewalld
  register: services_state

- name: Open port in firewalld
  firewalld: 
    port={{item}}/tcp
    permanent: true
    state: enabled
    immediate: yes
  when: services_state.status.ActiveState == 'running'
  ignore_errors: yes
  with_items:
  - 27017

- name: "SELinux port access should be granted"
  seport:
    ports: 27017
    proto: "tcp"
    setype: "mongod_port_t"
    state: "present"
  when: ansible_selinux.status == 'enabled'
  ignore_errors: yes

- name: SELinux port access should be granted for MongoDB
  shell: chcon -R --reference=/var/lib/mongo {{ dir_for_mongo_data }}
  when: ansible_selinux.status == 'enabled'
  ignore_errors: yes

- name: SELinux port access should be granted for MongoDB
  shell: "setsebool -P httpd_can_network_connect 1"
  when: ansible_selinux.status == 'enabled'  
  ignore_errors: yes





