---
- name: Install package and etc.
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nano
    - nc
    - mongodb-org
    - policycoreutils-python
  when: mongo_repo is success
  environment: "{{item}}"
  with_items: "{{proxy_env}}"
